CREATE TABLE IF NOT EXISTS players (
  id TEXT PRIMARY KEY,
  tour TEXT NOT NULL,
  discipline TEXT NOT NULL,
  rank INTEGER NOT NULL,
  previous_rank INTEGER,
  points INTEGER NOT NULL,
  ranking_as_of DATE NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  display_name TEXT NOT NULL,
  country_code CHAR(2) NOT NULL,
  date_of_birth DATE NOT NULL,
  height_cm INTEGER NOT NULL,
  handedness TEXT NOT NULL,
  backhand TEXT NOT NULL,
  turned_pro_year INTEGER NOT NULL,
  career_high_rank INTEGER NOT NULL,
  career_high_date DATE NOT NULL,
  career_titles INTEGER NOT NULL,
  grand_slam_titles INTEGER NOT NULL,
  ytd_wins INTEGER NOT NULL,
  ytd_losses INTEGER NOT NULL,
  prize_money_career_usd BIGINT NOT NULL,
  prize_money_ytd_usd BIGINT NOT NULL,
  photo_url TEXT,
  coach TEXT,
  birthplace TEXT,
  residence TEXT,
  bio TEXT
);
